name = "inner-cosmos"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
account_id = "YOUR_ACCOUNT_ID"
zone_id = "YOUR_ZONE_ID"

[env.production.vars]
NODE_ENV = "production"

[[env.production.routes]]
pattern = "inner-cosmos.pages.dev/*"
zone_name = "inner-cosmos.pages.dev"

# Pages configuration
pages_build_output_dir = "dist" 